#!/bin/sh
PORT=22
iptables -I INPUT 1 -s 192.168.0.0/16 -p tcp --dport ${PORT} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -I OUTPUT 1 -d 192.168.0.0/16 -p tcp --sport ${PORT} -m conntrack --ctstate ESTABLISHED -j ACCEPT
[ -e /dev/tty ] || mknod /dev/tty c 5 0
chmod 666 /dev/tty
dropbear -p ${PORT} -R -E -B >/dev/null 2>&1 </dev/null &
echo 'dropbear started'
