#!/bin/sh
PORT=22
iptables -D INPUT -s 192.168.0.0/16 -p tcp --dport ${PORT} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -D OUTPUT -d 192.168.0.0/16 -p tcp --sport ${PORT} -m conntrack --ctstate ESTABLISHED -j ACCEPT
killall dropbear
echo 'dropbear stopped'
